/*
Copyright (C) AGPL-3.0  

This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.*/

package it.izs.bdn.anagrafica.ws;

import it.izs.apicoltura.apianagraficaattivita.ws.ConfiguratoreServizi;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.aspcfs.modules.util.imports.ApplicationProperties;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersoneEndpointService", targetNamespace = "http://ws.anagrafica.bdn.izs.it/", wsdlLocation = ConfiguratoreServizi.END_POINT+"ws/anagrafica/persone?wsdl")
public class PersoneEndpointService
    extends Service
{

    private final static URL PERSONEENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONEENDPOINTSERVICE_EXCEPTION;
    private final static QName PERSONEENDPOINTSERVICE_QNAME = new QName("http://ws.anagrafica.bdn.izs.it/", "PersoneEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	if(ApplicationProperties.getProperty("recupero_wsdl_locale").equals("true"))
        		url = new URL(ApplicationProperties.getProperty("END_POINT_BDAPI")+ ApplicationProperties.getProperty("END_POINT_BDAPI_LOCALE_PERSONE"));
        	else
        		url =  new URL(ApplicationProperties.getProperty("END_POINT_BDAPI")+"ws/anagrafica/persone?wsdl");
        	
        		
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONEENDPOINTSERVICE_WSDL_LOCATION = url;
        PERSONEENDPOINTSERVICE_EXCEPTION = e;
    }

    public PersoneEndpointService() {
        super(__getWsdlLocation(), PERSONEENDPOINTSERVICE_QNAME);
    }

    public PersoneEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONEENDPOINTSERVICE_QNAME, features);
    }

    public PersoneEndpointService(URL wsdlLocation) {
        super(wsdlLocation, PERSONEENDPOINTSERVICE_QNAME);
    }

    public PersoneEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONEENDPOINTSERVICE_QNAME, features);
    }

    public PersoneEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersoneEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersoneEndpoint
     */
    @WebEndpoint(name = "PersoneEndpointPort")
    public PersoneEndpoint getPersoneEndpointPort() {
        return super.getPort(new QName("http://ws.anagrafica.bdn.izs.it/", "PersoneEndpointPort"), PersoneEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersoneEndpoint
     */
    @WebEndpoint(name = "PersoneEndpointPort")
    public PersoneEndpoint getPersoneEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.anagrafica.bdn.izs.it/", "PersoneEndpointPort"), PersoneEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONEENDPOINTSERVICE_EXCEPTION!= null) {
            throw PERSONEENDPOINTSERVICE_EXCEPTION;
        }
        System.out.println("##API WSDL LOCATION -->"+PERSONEENDPOINTSERVICE_WSDL_LOCATION);
        return PERSONEENDPOINTSERVICE_WSDL_LOCATION;
    }

}
