/*
Copyright (C) AGPL-3.0  

This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.*/

package it.izs.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "controlliallevamentiService", targetNamespace = "http://ws.izs.it", wsdlLocation = "https://ws.izs.it/j6_controlli/ws/ispezioni/controlliallevamenti.ws?wsdl")
public class ControlliallevamentiService
    extends Service
{

    private final static URL CONTROLLIALLEVAMENTISERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLLIALLEVAMENTISERVICE_EXCEPTION;
    private final static QName CONTROLLIALLEVAMENTISERVICE_QNAME = new QName("http://ws.izs.it", "controlliallevamentiService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ws.izs.it/j6_controlli/ws/ispezioni/controlliallevamenti.ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLLIALLEVAMENTISERVICE_WSDL_LOCATION = url;
        CONTROLLIALLEVAMENTISERVICE_EXCEPTION = e;
    }

    public ControlliallevamentiService() {
        super(__getWsdlLocation(), CONTROLLIALLEVAMENTISERVICE_QNAME);
    }

    public ControlliallevamentiService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLLIALLEVAMENTISERVICE_QNAME, features);
    }

    public ControlliallevamentiService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLLIALLEVAMENTISERVICE_QNAME);
    }

    public ControlliallevamentiService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLLIALLEVAMENTISERVICE_QNAME, features);
    }

    public ControlliallevamentiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControlliallevamentiService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Controlliallevamenti
     */
    @WebEndpoint(name = "controlliallevamentiPort")
    public Controlliallevamenti getControlliallevamentiPort() {
        return super.getPort(new QName("http://ws.izs.it", "controlliallevamentiPort"), Controlliallevamenti.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Controlliallevamenti
     */
    @WebEndpoint(name = "controlliallevamentiPort")
    public Controlliallevamenti getControlliallevamentiPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.izs.it", "controlliallevamentiPort"), Controlliallevamenti.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLLIALLEVAMENTISERVICE_EXCEPTION!= null) {
            throw CONTROLLIALLEVAMENTISERVICE_EXCEPTION;
        }
        return CONTROLLIALLEVAMENTISERVICE_WSDL_LOCATION;
    }

}
