/*
Copyright (C) AGPL-3.0  

This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.*/

package it.izs.apicoltura.apianagraficaattivita.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;




/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ApiEndpoint", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApiEndpoint {


    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.ElencoApiariApicoltoriFuoriRegioneResponse
     */
    @WebMethod
    @WebResult(name = "elencoApiariApicoltoriFuoriRegioneResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/elencoApiariApicoltoriFuoriRegioneRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/elencoApiariApicoltoriFuoriRegioneResponse")
    public ElencoApiariApicoltoriFuoriRegioneResponse elencoApiariApicoltoriFuoriRegione(
        @WebParam(name = "elencoApiariApicoltoriFuoriRegione", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        ElencoApiariApicoltoriFuoriRegione parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS);

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.InsertApiarioResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "insertApiarioResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/insertApiarioRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/insertApiarioResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/insertApiario/Fault/BusinessWsException")
    })
    public InsertApiarioResponse insertApiario(
        @WebParam(name = "insertApiario", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        InsertApiario parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.UpdateApiarioResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "updateApiarioResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/updateApiarioRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/updateApiarioResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/updateApiario/Fault/BusinessWsException")
    })
    public UpdateApiarioResponse updateApiario(
        @WebParam(name = "updateApiario", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        UpdateApiario parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.DeleteApiarioResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteApiarioResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/deleteApiarioRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/deleteApiarioResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/deleteApiario/Fault/BusinessWsException")
    })
    public DeleteApiarioResponse deleteApiario(
        @WebParam(name = "deleteApiario", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        DeleteApiario parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.SearchApiResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchApiResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/searchApiRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/searchApiResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/searchApi/Fault/BusinessWsException")
    })
    public SearchApiResponse searchApi(
        @WebParam(name = "searchApi", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        SearchApi parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.SearchApiByPkResponse
     */
    @WebMethod
    @WebResult(name = "searchApiByPkResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/searchApiByPkRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApiEndpoint/searchApiByPkResponse")
    public SearchApiByPkResponse searchApiByPk(
        @WebParam(name = "searchApiByPk", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        SearchApiByPk parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS);

}
