/*
Copyright (C) AGPL-3.0  

This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.*/

package it.izs.apicoltura.apianagraficaattivita.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

 
/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ApistodetEndpoint", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApistodetEndpoint {


    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.InsertStoricoDetentoreResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "insertStoricoDetentoreResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApistodetEndpoint/insertStoricoDetentoreRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApistodetEndpoint/insertStoricoDetentoreResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApistodetEndpoint/insertStoricoDetentore/Fault/BusinessWsException")
    })
    public InsertStoricoDetentoreResponse insertStoricoDetentore(
        @WebParam(name = "insertStoricoDetentore", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        InsertStoricoDetentore parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.UpdateStoricoDetentoreResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "updateStoricoDetentoreResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApistodetEndpoint/updateStoricoDetentoreRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApistodetEndpoint/updateStoricoDetentoreResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApistodetEndpoint/updateStoricoDetentore/Fault/BusinessWsException")
    })
    public UpdateStoricoDetentoreResponse updateStoricoDetentore(
        @WebParam(name = "updateStoricoDetentore", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        UpdateStoricoDetentore parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.DeleteStoricoDetentoreResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteStoricoDetentoreResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApistodetEndpoint/deleteStoricoDetentoreRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApistodetEndpoint/deleteStoricoDetentoreResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApistodetEndpoint/deleteStoricoDetentore/Fault/BusinessWsException")
    })
    public DeleteStoricoDetentoreResponse deleteStoricoDetentore(
        @WebParam(name = "deleteStoricoDetentore", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        DeleteStoricoDetentore parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.SearchStoricoDetentoreResponse
     * @throws BusinessWsException_Exception
     */
    @WebMethod
    @WebResult(name = "searchStoricoDetentoreResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApistodetEndpoint/searchStoricoDetentoreRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApistodetEndpoint/searchStoricoDetentoreResponse", fault = {
        @FaultAction(className = BusinessWsException_Exception.class, value = "http://ws.apianagrafica.apicoltura.izs.it/ApistodetEndpoint/searchStoricoDetentore/Fault/BusinessWsException")
    })
    public SearchStoricoDetentoreResponse searchStoricoDetentore(
        @WebParam(name = "searchStoricoDetentore", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        SearchStoricoDetentore parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS)
        throws BusinessWsException_Exception
    ;

    /**
     * 
     * @param soapAutenticazioneWS
     * @param parameters
     * @return
     *     returns it.izs.apicoltura.apianagraficaattivita.ws.SearchStoricoDetentoreByPkResponse
     */
    @WebMethod
    @WebResult(name = "searchStoricoDetentoreByPkResponse", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "result")
    @Action(input = "http://ws.apianagrafica.apicoltura.izs.it/ApistodetEndpoint/searchStoricoDetentoreByPkRequest", output = "http://ws.apianagrafica.apicoltura.izs.it/ApistodetEndpoint/searchStoricoDetentoreByPkResponse")
    public SearchStoricoDetentoreByPkResponse searchStoricoDetentoreByPk(
        @WebParam(name = "searchStoricoDetentoreByPk", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", partName = "parameters")
        SearchStoricoDetentoreByPk parameters,
        @WebParam(name = "SOAPAutenticazioneWS", targetNamespace = "http://ws.apianagrafica.apicoltura.izs.it/", header = true, partName = "SOAPAutenticazioneWS")
        SOAPAutenticazioneWS soapAutenticazioneWS);

}
